# Generated by Django 6.0.7 on 2026-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='25 mins', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='youtube_query',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
