# Generated by Django 6.0.7 on 2026-08-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_difficulty_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
