# Generated by Django 6.0.7 on 2026-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.TextField(blank=True, default='', help_text='JSON string of calorie and macro metrics'),
        ),
    ]
